### ISSUE TITLE
fix scrollbar

### ISSUE THREAD

**Issue by Suvitruf** [EverythingMe/OverScrollView#1]
Hello. 
Even in top (or bottom)  position scrollbar indicator shown somewhere in middle. 
This confuse the user...

Can you fix it?

**Comment by rotemmiz** [comment]
Sorry for the delayed response. The reason it's in the middle is the fact that there's a large padding in both top and bottom of the main layout inside the ScrollView, its length is included inside the scroller. 
I can certainly remove the indicator altogether, not sure I can fool the indicator as it's part of `Scroller`. I'll give it a look as soon as I can.

**Comment by rotemmiz** [comment]
Hey, 
I have deprecated this project, please take a look at https://github.com/EverythingMe/overscroll-decor instead, it's a much more flexible library.
