### ISSUE TITLE
SwipeRefresh Issue

### ISSUE THREAD

**Issue by bahacan19** [EverythingMe/OverScrollView#7]
How can i use this class with [this Google's SwipeRefreshLayout](http://developer.android.com/training/swipe/add-swipe-interface.html)

**Comment by rotemmiz** [comment]
I can't see how both can interact with each other.
Each of them represent a different visual reaction to the user's overscroll action, I think adding both is quite confusing.

Anyway, try using https://github.com/EverythingMe/overscroll-decor, it's a much more flexible implementation of over scroll (I think you can add the decor on top of SwipeRefreshLayout).

**Comment by bahacan19** [comment]
@rotemmiz I want this case: When i pull down swiperefreshlayout refreshes and when i pull up overscrollview bounces. How can i pass the pull down event to the swiperefreshlayout?
